package us.beiyue.beilindataportability.common;

import us.beiyue.beilindataportability.common.nbt.NbtCompound;
import us.beiyue.beilindataportability.common.nbt.NbtIo;
import us.beiyue.beilindataportability.common.nbt.NbtList;
import us.beiyue.beilindataportability.common.nbt.NbtLongArray;
import us.beiyue.beilindataportability.common.nbt.NbtValue;

import java.io.IOException;
import java.io.OutputStream;
import java.time.Instant;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class LitematicWriter {
	private static final int LITEMATICA_VERSION = 6;
	private static final int LITEMATICA_SUB_VERSION = 1;
	private static final int DATA_VERSION_1_20_1 = 3465;

	private LitematicWriter() {
	}

	public static void write(ComponentExport component, String author, OutputStream output) throws IOException {
		ComponentSummary s = component.summary;
		int sizeX = Math.max(1, s.maxX - s.minX + 1);
		int sizeY = Math.max(1, s.maxY - s.minY + 1);
		int sizeZ = Math.max(1, s.maxZ - s.minZ + 1);
		int volume = safeVolume(sizeX, sizeY, sizeZ);

		Palette palette = Palette.fromBlocks(component.blocks);
		int bitsPerEntry = Math.max(2, 32 - Integer.numberOfLeadingZeros(Math.max(1, palette.size() - 1)));
		long[] blockStates = packBlockStates(component.blocks, palette, s.minX, s.minY, s.minZ, sizeX, sizeY, sizeZ, bitsPerEntry);
		long nowMs = Instant.now().toEpochMilli();

		NbtCompound root = new NbtCompound()
			.putInt("MinecraftDataVersion", DATA_VERSION_1_20_1)
			.putInt("Version", LITEMATICA_VERSION)
			.putInt("SubVersion", LITEMATICA_SUB_VERSION);

		NbtCompound metadata = new NbtCompound()
			.putString("Author", author != null && !author.isBlank() ? author : "Beilin Data Portability")
			.putString("Description", "Generated by Beilin Data Portability")
			.put("EnclosingSize", vector(sizeX, sizeY, sizeZ))
			.putString("Name", s.filename != null ? s.filename.replace(".litematic", "") : "beilin-export")
			.putInt("RegionCount", 1)
			.putLong("TimeCreated", nowMs)
			.putLong("TimeModified", nowMs)
			.putInt("TotalBlocks", component.blocks.size())
			.putInt("TotalVolume", volume);

		NbtCompound region = new NbtCompound()
			.put("BlockStatePalette", palette.toNbtList())
			.put("BlockStates", new NbtLongArray(blockStates))
			.put("Entities", new NbtList(NbtValue.COMPOUND))
			.put("PendingBlockTicks", new NbtList(NbtValue.COMPOUND))
			.put("PendingFluidTicks", new NbtList(NbtValue.COMPOUND))
			.put("Position", vector(0, 0, 0))
			.put("Size", vector(sizeX, sizeY, sizeZ))
			.put("TileEntities", new NbtList(NbtValue.COMPOUND));

		NbtCompound regions = new NbtCompound()
			.put("Region 0", region);

		root.put("Metadata", metadata)
			.put("Regions", regions);

		NbtIo.writeCompressed(root, "", output);
	}

	private static NbtCompound vector(int x, int y, int z) {
		return new NbtCompound()
			.putInt("x", x)
			.putInt("y", y)
			.putInt("z", z);
	}

	private static int safeVolume(int x, int y, int z) {
		long v = (long) x * (long) y * (long) z;
		if (v > Integer.MAX_VALUE) throw new IllegalArgumentException("Component volume is too large for MVP litematic writer");
		return (int) v;
	}

	private static long[] packBlockStates(
		List<BlockRecord> blocks,
		Palette palette,
		int minX,
		int minY,
		int minZ,
		int sizeX,
		int sizeY,
		int sizeZ,
		int bitsPerEntry
	) {
		int volume = safeVolume(sizeX, sizeY, sizeZ);
		long[] out = new long[(int) Math.ceil((double) volume * bitsPerEntry / 64.0D)];
		long mask = (1L << bitsPerEntry) - 1L;
		for (BlockRecord b : blocks) {
			int lx = b.x - minX;
			int ly = b.y - minY;
			int lz = b.z - minZ;
			if (lx < 0 || ly < 0 || lz < 0 || lx >= sizeX || ly >= sizeY || lz >= sizeZ) continue;
			int index = (ly * sizeZ + lz) * sizeX + lx;
			int paletteId = palette.indexOf(b.blockState);
			long value = ((long) paletteId) & mask;
			int bitIndex = index * bitsPerEntry;
			int longIndex = bitIndex >>> 6;
			int bitOffset = bitIndex & 63;
			out[longIndex] |= value << bitOffset;
			int spill = bitOffset + bitsPerEntry - 64;
			if (spill > 0 && longIndex + 1 < out.length) {
				out[longIndex + 1] |= value >>> (bitsPerEntry - spill);
			}
		}
		return out;
	}

	private static final class Palette {
		private final LinkedHashMap<String, Integer> ids = new LinkedHashMap<>();

		private Palette() {
			ids.put("minecraft:air", 0);
		}

		static Palette fromBlocks(List<BlockRecord> blocks) {
			Palette p = new Palette();
			for (BlockRecord b : blocks) {
				p.indexOf(b.blockState);
			}
			return p;
		}

		int size() {
			return ids.size();
		}

		int indexOf(String blockState) {
			String normalized = normalizeBlockState(blockState);
			Integer existing = ids.get(normalized);
			if (existing != null) return existing;
			int next = ids.size();
			ids.put(normalized, next);
			return next;
		}

		NbtList toNbtList() {
			NbtList list = new NbtList(NbtValue.COMPOUND);
			for (String state : ids.keySet()) {
				ParsedState parsed = ParsedState.parse(state);
				NbtCompound c = new NbtCompound().putString("Name", parsed.name);
				if (!parsed.properties.isEmpty()) {
					NbtCompound props = new NbtCompound();
					for (Map.Entry<String, String> e : parsed.properties.entrySet()) {
						props.putString(e.getKey(), e.getValue());
					}
					c.put("Properties", props);
				}
				list.add(c);
			}
			return list;
		}
	}

	private static String normalizeBlockState(String raw) {
		if (raw == null || raw.isBlank()) return "minecraft:air";
		String s = raw.trim();
		if (s.startsWith("Block{")) {
			int start = s.indexOf('{');
			int end = s.indexOf('}');
			if (start >= 0 && end > start) {
				return s.substring(start + 1, end) + s.substring(end + 1);
			}
		}
		return s;
	}

	private static final class ParsedState {
		final String name;
		final Map<String, String> properties;

		private ParsedState(String name, Map<String, String> properties) {
			this.name = name;
			this.properties = properties;
		}

		static ParsedState parse(String state) {
			String s = normalizeBlockState(state);
			int propStart = s.indexOf('[');
			if (propStart < 0 || !s.endsWith("]")) {
				return new ParsedState(withNamespace(s), Map.of());
			}
			String name = withNamespace(s.substring(0, propStart));
			String rawProps = s.substring(propStart + 1, s.length() - 1);
			Map<String, String> props = new HashMap<>();
			if (!rawProps.isBlank()) {
				for (String part : rawProps.split(",")) {
					int idx = part.indexOf('=');
					if (idx <= 0 || idx >= part.length() - 1) continue;
					props.put(part.substring(0, idx), part.substring(idx + 1));
				}
			}
			return new ParsedState(name, props);
		}

		private static String withNamespace(String name) {
			if (name == null || name.isBlank()) return "minecraft:air";
			return name.indexOf(':') >= 0 ? name : "minecraft:" + name;
		}
	}
}
